# -*- coding: utf-8 -*-
"""TP4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G3ugEDiMZt8rEH_3PoK245bmLHBcuiJl

# TP N°.4 - Generación de funciones de densidad de probabilidad mediante el uso de Google Colab y Python.
| # | Integrantes |
|---|---|
| 1 | Juan Martin Terrizzi |
| 2 | Ignacio Martinez Beraza |
| 3 | Yoel Ibarra |
| 4 | German Agustin Lechner |

## Objetivo
El trabajo propuesto consiste en que el grupo realice una selección de un set de datos de interés, el procesamiento de datos del mismo, la obtención de una función de densidad de probabilidad que ajuste dichos datos y la presentación del análisis realizado. Este dataset será a su vez el que se utilizará para la simulación a realizar en el TP Nª 5 (Obligatorio).

## Descripción
1. El grupo deberá seleccionar un set de datos de interés que quedará sujeto a la aprobación de la cátedra. El mismo deberá contar con al menos 3000 registros.
2. Mediante un notebook de Google Colab realizar el procesamiento del set de datos utilizando Python y todas las bibliotecas necesarias, acorde a la necesidad de generar uno o varios dataframes adecuados para el posterior ajuste. Incluir en esta etapa el análisis exploratorio de datos que considere necesario (gráficos, métricas, etc).
3. Realizar el ajuste de los dataframes procesados para obtener funciones de densidad de probabilidad, y seleccionar las mejores alternativas.
4. Con la(s) función(es) obtenida(s) generar un set de datos y verificar mediante histograma o una muestra que los datos simulados tienen correlación con los datos de origen.
5. Realizar una conclusión final sobre el trabajo realizado y sus apreciaciones personales.

Un integrante de cada grupo deberá realizar una exposición oral de no más de 5 minutos en donde muestre el notebook de Google Colab a modo de informe y presentación, en donde incluya una explicación sobre los datos, los pasos de procesamiento realizados, el ajuste realizado y las conclusiones finales.

# 1. Carga de Bibliotecas

Seccion para instalar e importar bibliotecas necesarias
"""

#pip install fitter

from fitter import Fitter
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from scipy import stats

#from google.colab import drive
#drive.mount('/content/drive')

"""#2. Carga de Datos

"""
PATH_CSV_MAIN_DRIVE = '/content/drive/MyDrive/Colab Notebooks/TPs/TP4/Datos/Hospital ER_Data.csv'
PATH_CSV_MAIN = ''

Atenciones_ER = pd.read_csv(PATH_CSV_MAIN_DRIVE)

"""#3. Análisis Exploratorio de Datos

Consultando el tipo de dato del archivo cargado podemos ver que corresponde a un dataframe de la libreria pandas.
"""

type(Atenciones_ER)

"""Mediante el metodo `.head()` podemos inspeccionar los primeros 100 registros del dataframe cargado."""

Atenciones_ER.head()

Atenciones_ER.columns

Atenciones_ER['Department Referral'].value_counts()

Atenciones_ER.shape

Atenciones_ER.dtypes

"""#4. Preparación de Datos

## Intervalo entre llegadas

Convertimos la columna de fecha (que estaba como texto) a un tipo datetime de pandas, y luego ordena todo el dataframe cronológicamente.
"""

Atenciones_ER['PatientAdmissionDate_dt'] = pd.to_datetime(Atenciones_ER['Patient Admission Date'])

"""Reseteamos el índice para que quede limpio del '0' en adelante."""

Atenciones_ER = Atenciones_ER.sort_values('PatientAdmissionDate_dt').reset_index(drop=True)

"""Como el dataframe ya está ordenado cronológicamente,
`.diff()` calcula la diferencia entre *fecha/hora* de un paciente y el anterior. Eso da el tiempo entre llegadas consecutivas. Luego lo convierte a minutos dividiendo por 60.
Esta columna `IA_min` es clave para la simulación, ya que representa el intervalo entre arribos a la sala de emergencias.
"""

Atenciones_ER['IA_min'] = Atenciones_ER['PatientAdmissionDate_dt'].diff().dt.total_seconds() / 60
Atenciones_ER = Atenciones_ER.dropna(subset=['IA_min']) #eliminar NaN

"""Obtenemos dos visualizaciones del intervalo entre llegadas. El histograma con `50 bins` da una idea de la forma de la distribución, y el boxplot permite ver la mediana, dispersión y outliers."""

Atenciones_ER.hist('IA_min', bins=50)

"""### Boxplot
Al observar el Boxplot de los intervalos entre llegadas (IA_min), notamos una caja muy comprimida cerca del cero. Esto nos indica que el flujo de pacientes es intenso y frecuente. Sin embargo, la gran cantidad de valores atípicos (outliers) representados por los puntos superiores, nos muestra que el sistema también enfrenta periodos de inactividad prolongada. Esta dispersión es la que luego intentaremos modelar matemáticamente en el punto 5 para que nuestra simulación sea realista y no solo un promedio simple
"""

Atenciones_ER.boxplot('IA_min')

"""## Tiempo de espera

Hacemos lo mismo pero para el tiempo de espera del paciente, que ya venía en el dataset original. Utilizamos `bins=10` porque los valores están entre 10 y 60 minutos, simulando bloques de 5 minutos cada bin, lo cual sirve para ver la distribución de forma clara.
"""

Atenciones_ER.hist('Patient Waittime', bins=10)
# Como tenemos entre 10 y 60 minutos de tiempo de espera, utilizamos un bins = 10 para simular bloques de 5 minutos

Atenciones_ER.boxplot('Patient Waittime')

"""## 5. Cálculo de FDPs

Para la obtencion de las respectivas f.d.p utilizamos la libreria *Fitter* de python con un `bins=10`, la cual nos permite ajustar automaticamente los datos a multiples distribuciones.
"""

fdp_WT = Fitter(Atenciones_ER['Patient Waittime'], bins=10)

fdp_WT.fit()

"""Una vez obtenidas todas las distribuciones ajustadas mediante la libreria, filtramos las 10 mejores con ayuda del metodo `.summary(10)`. Esto nos revela que la distribucion *kappa4* es mejor para nuestros datos del csv."""

fdp_WT.summary(10)

"""Hacemos lo mismo con el intervalo entre llegadas."""

fdp_IA = Fitter(Atenciones_ER.IA_min)

fdp_IA.fit()

"""Para esta variable, nos termina dando que la mejor distribucion para ajustar los datos es la *genhyperbolic*."""

fdp_IA.summary(10)

"""## 6. Simulación

Una vez que tenemos las respectivas funciones de densidad, procedemos con la generacion de datos simulados.
"""

N = len(Atenciones_ER)   # misma cantidad que el dataset original
np.random.seed(42)       # reproducibilidad

# ── Patient Waittime mejor fit: kappa4
params_wt = fdp_WT.get_best()                 # dict con distribución ganadora y parámetros
best_dist_wt_name = list(params_wt.keys())[0]
best_params_wt    = params_wt[best_dist_wt_name]
dist_wt = getattr(stats, best_dist_wt_name)   # objeto scipy de la distribución

datos_sim_wt = dist_wt.rvs(*best_params_wt.values(), size=N)

print(f"Distribución WT  : {best_dist_wt_name}")
print(f"Parámetros       : {best_params_wt}")
print(f"Datos generados  : {len(datos_sim_wt)}")

# ── IA_min mejor fit: genhyperbolic
params_ia = fdp_IA.get_best()
best_dist_ia_name = list(params_ia.keys())[0]
best_params_ia    = params_ia[best_dist_ia_name]
dist_ia = getattr(stats, best_dist_ia_name)

datos_sim_ia = dist_ia.rvs(*best_params_ia.values(), size=N)

print(f"\nDistribución IA  : {best_dist_ia_name}")
print(f"Parámetros       : {best_params_ia}")
print(f"Datos generados  : {len(datos_sim_ia)}")

"""Para visualizar la calidad de los datos simulados en comparacion de realizamos un histograma que a simple vista nos ayude a determinar esto ultimo."""

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("Punto 4 — Comparación datos originales vs simulados", fontsize=14)

# Patient Waittime
ax = axes[0]
ax.hist(Atenciones_ER['Patient Waittime'], bins=10, density=True,
        alpha=0.5, color='steelblue', label='Original')
ax.hist(datos_sim_wt, bins=10, density=True,
        alpha=0.5, color='tomato', label='Simulado')
ax.set_title(f"Patient Waittime — {best_dist_wt_name}")
ax.set_xlabel("Minutos de espera")
ax.set_ylabel("Densidad")
ax.legend()

# IA_min
ax = axes[1]
ax.hist(Atenciones_ER['IA_min'], bins=50, density=True,
        alpha=0.5, color='steelblue', label='Original')
ax.hist(datos_sim_ia, bins=50, density=True,
        alpha=0.5, color='tomato', label='Simulado')
ax.set_title(f"IA_min — {best_dist_ia_name}")
ax.set_xlabel("Minutos entre llegadas")
ax.set_ylabel("Densidad")
ax.legend()

plt.tight_layout()
plt.show()